#include <iostream>
#include "Melody.h"
using namespace std;
#undef main

int main()
{

	Note notes[48] = { {PAUSE,EIGHTH},{A,EIGHTH},{D2,EIGHTH},{F2,EIGHTH},{E2,EIGHTH},{D2,EIGHTH},{F2,EIGHTH},{D2,EIGHTH},{E2,EIGHTH},
	{D2,EIGHTH},{B_BEM,EIGHTH},{C2,EIGHTH},{A,HALF}, {PAUSE, EIGHTH}, {A, EIGHTH}, {D2,EIGHTH},{F2,EIGHTH},{E2,EIGHTH},{D2,EIGHTH},
	{F2,EIGHTH}, {D2,EIGHTH},{E2,EIGHTH},{D2,EIGHTH},{A,EIGHTH}, {A_BEM,EIGHTH}, {G,HALF}, {PAUSE, EIGHTH}, {G,EIGHTH}, {B_BEM,EIGHTH},
	{C2sh, EIGHTH}, {E2, HALF}, {PAUSE,EIGHTH}, {G,EIGHTH}, {B_BEM,EIGHTH}, {C2sh, EIGHTH}, {D2, HALF},{PAUSE,EIGHTH}, {D,EIGHTH}, {F,EIGHTH}, {C2, EIGHTH},
	{B_BEM,EIGHTH}, {A, EIGHTH}, {C2,EIGHTH}, {B_BEM, EIGHTH}, {B_BEM, EIGHTH}, {A, EIGHTH}, {A,EIGHTH}, {Csh,EIGHTH} };
	
	
	
	
	Note third[2] = { {A,WHOLE}, {A,WHOLE} };
	
	Note doo[42] = { {D_LIT, EIGHTH}, {F_LIT, EIGHTH}, {A_LIT, EIGHTH}, {F_LIT, EIGHTH}, {D_LIT, EIGHTH}, {F_LIT, EIGHTH}, {A_LIT, EIGHTH}, {F_LIT, EIGHTH},
	{G_LIT, EIGHTH}, {B_LIT,EIGHTH}, {D,EIGHTH}, {B_LIT, EIGHTH}, {D_LIT, EIGHTH}, {F_LIT, EIGHTH}, {A_LIT, EIGHTH}, {F_LIT, EIGHTH},
	{D_LIT,HALF}, {D_LIT, EIGHTH}, {F_LIT, EIGHTH}, {A_LIT, EIGHTH}, {F_LIT, EIGHTH},
	{D_LIT,HALF},{G_LIT, EIGHTH}, {B_LIT,EIGHTH}, {D,EIGHTH}, {B_LIT, EIGHTH}, {G_LIT, HALF}, {G_LIT, EIGHTH}, {B_LIT,EIGHTH}, {D,EIGHTH}, {B_LIT, EIGHTH}, {G_LIT, HALF},
	{D_LIT, EIGHTH}, {F_LIT, EIGHTH}, {A_LIT, EIGHTH}, {F_LIT, EIGHTH} ,{D_LIT, HALF}, {A_BIG, EIGHTH}, {Csh_LIT, EIGHTH}, {E_LIT, EIGHTH},
	{Csh_LIT, EIGHTH}, {A_BIG, HALF} };

	Channel chan[2] = {{doo,42},{notes,48} };
	Channel chan1[2] = { {notes,48},{third,2} };
	Melody melody(chan, 2);

	melody.play();

	return 0;
}/*{G,QUARTER}, {G,QUARTER}, {G,QUARTER}, {C2,HEX}, {B,HEX}, {A,HEX},
	{G,HEX},{F,QUARTER},{D2,QUARTER}, {F,HALF}, {E,QUARTER}, {E,QUARTER},{E,QUARTER},
	{A,HEX},{G,HEX},{F,HEX},{E,HEX},{D,QUARTER},{A,QUARTER},{D,QUARTER}*/
	
	
	
	//{B,QUARTER}, {E2,QUARTER},{B,QUARTER}, {C2,EIGHTH},{D2,EIGHTH},
	//{D2,QUARTER},{A,QUARTER},{B,HALF}, {B,EIGHTH},{E2,EIGHTH},{B,EIGHTH},{C2,EIGHTH},
	//{D2,EIGHTH},{D2,EIGHTH},{C2,EIGHTH},{B,EIGHTH},{C2,EIGHTH},{D2,EIGHTH},{C2,EIGHTH},
	//{A,EIGHTH},{B,HALF}
	
	
	//{G,QUARTER}, {G,QUARTER}, {G,QUARTER}, {C2,HEX}, {B,HEX}, {A,HEX},
	//{G,HEX},{F,QUARTER},{D2,QUARTER}, {F,HALF}, {E,QUARTER}, {E,QUARTER},{E,QUARTER},
	//{A,HEX},{G,HEX},{F,HEX},{E,HEX},{D,QUARTER},{A,QUARTER},{D,QUARTER} };
	